services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: impulse_club_api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=Host=localhost;Port=5432;Database=impulseclubdb;Username=impulseclubuser;Password=supersecret
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - impulse_network

  postgres:
    image: postgres:16-alpine
    container_name: impulse_club_db
    environment:
      POSTGRES_DB: impulseclubdb
      POSTGRES_USER: impulseclubuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - impulse_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U impulseclubuser -d impulseclubdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

